import 'package:cars_right/core/widgets/header_bottom.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:step_progress_indicator/step_progress_indicator.dart';

class InspectionReportBottomSheet extends StatelessWidget {
  const InspectionReportBottomSheet({super.key});

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableSheet(
      initialChildSize: 0.95,
      minChildSize: 0.60,
      maxChildSize: 0.95,
      builder: (context, scrollController) {
        return Container(
          decoration: const BoxDecoration(
            color: Color(0xFFEFF4F8),
            borderRadius: BorderRadius.vertical(
              top: Radius.circular(34),
            ),
          ),
          child: Column(
            children: [
              const Header(
                title: 'Inspection Report',
                subTitle: 'Vehicle Check Report',
              ),
              Expanded(
                child: Container(
                  margin: const EdgeInsets.only(left: 10, right: 10, top: 4),
                  decoration: BoxDecoration(color: Colors.white, boxShadow: [
                    BoxShadow(
                      color: Colors.grey.withOpacity(.4),
                      blurRadius: 10,
                    ),
                  ]),
                  child: ListView(
                    controller: scrollController,
                    padding: const EdgeInsets.all(12),
                    children: [
                      Row(
                        children: [
                          Image.asset('images/carsright.png',
                              height: 90, width: 90),
                          const SizedBox(width: 5),
                          const Expanded(
                            child: Text(
                              'VEHICLE INSPECTION REPORT',
                              style: TextStyle(
                                color: Color(0xFF101828),
                                fontSize: 11,
                                fontWeight: FontWeight.w900,
                                letterSpacing: 1,
                              ),
                            ),
                          ),
                          const Text(
                            'CR-4W-2026-00184',
                            style: TextStyle(
                              color: Color(0xFF22A7C7),
                              fontSize: 11,
                              fontWeight: FontWeight.w900,
                              letterSpacing: 1,
                            ),
                          ),
                        ],
                      ),
                      const Align(
                        alignment: Alignment.centerRight,
                        child: Text(
                          'Inspection Date: 07/01/2026',
                          style: TextStyle(
                            color: Color(0xFF667085),
                            fontSize: 14,
                            fontWeight: FontWeight.w800,
                          ),
                        ),
                      ),
                      const Divider(
                        height: 24,
                        thickness: 3,
                        color: Color(0xFF22A7C7),
                      ),
                      const SizedBox(height: 2),
                      const ReportMainCard(),
                      const SizedBox(height: 16),
                      const ConditionScoreInfoSection(),
                      const SizedBox(height: 16),
                      const VehicleDetailsSection(),
                      const SizedBox(height: 16),
                      const TechnicalInspectionSection(),
                      const SizedBox(height: 16),
                      const InspectionImagesSection(),
                      const SizedBox(height: 16),
                      const ValuationRemarksSection(),
                      const Padding(
                        padding: EdgeInsets.all(8.0),
                        child: Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Expanded(
                              child: Text(
                                'This certified report is generated by Cars Right \nInspection System. Data is timestamped and \ngeo-verified at inspection time.',
                                style: TextStyle(
                                  color: Color(0xFF667085),
                                  fontSize: 11,
                                ),
                              ),
                            ),
                            Text(
                              'Page 1/1',
                              style: TextStyle(
                                color: Color(0xFF22A7C7),
                                fontSize: 13,
                              ),
                            )
                          ],
                        ),
                      )
                    ],
                  ),
                ),
              ),
            ],
          ),
        );
      },
    );
  }
}

class ReportMainCard extends StatelessWidget {
  const ReportMainCard({super.key});

  @override
  Widget build(BuildContext context) {
    return _sectionBox(
      child: Container(
        decoration: const BoxDecoration(color: Colors.white),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Stack(
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(4),
                  child: Image.asset(
                    'images/onboarding/img1.jpg',
                    height: 210,
                    width: double.infinity,
                    fit: BoxFit.cover,
                  ),
                ),
                Positioned(
                  bottom: 10,
                  left: 10,
                  child: Container(
                    padding: const EdgeInsets.all(2),
                    decoration: const BoxDecoration(color: Color(0xff697489)),
                    child: const Text(
                      'CAPTURED VEHICLE IMAGE',
                      style: TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                )
              ],
            ),
            const SizedBox(height: 16),
            const Text(
              'PRIVATE - REPO',
              style: TextStyle(
                color: Color(0xFF22A7C7),
                fontSize: 16,
                fontWeight: FontWeight.bold,
                letterSpacing: 1.5,
              ),
            ),
            const Text(
              'Ford EcoSport 1.5 Titanium',
              style: TextStyle(
                  color: Color(0xFF07558E),
                  fontSize: 27,
                  fontWeight: FontWeight.bold,
                  letterSpacing: .2),
            ),
            const Text(
              'TN 05 KK 1100 - Petrol - Manual - Chennai',
              style: TextStyle(
                color: Color(0xFF54828E),
                fontSize: 15,
                fontWeight: FontWeight.w800,
              ),
            ),
            const SizedBox(height: 16),
            _priceBox('VALUATION PRICE', 'Rs 6,80,000', 30),
            const SizedBox(height: 8),
            _greenTick('No Damage Reported'),
            const SizedBox(height: 4),
            _greenTick('Running Condition'),
          ],
        ),
      ),
    );
  }
}

class VehicleDetailsSection extends StatelessWidget {
  const VehicleDetailsSection({super.key});

  @override
  Widget build(BuildContext context) {
    return _sectionBox(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _sectionTitle('VEHICLE DETAILS'),
          _twoColumn('REGISTRATION NO.', 'TN 05 KK 1100', 'VEHICLE TYPE', '4W'),
          _twoColumn('ODOMETER / HOURS', '38,420 km', 'FUEL / TRANSMISSION',
              'Petrol / Manual'),
          _twoColumn(
              'CHASSIS NO.', 'MAJAXXMRKAM*****', 'ENGINE NO.', 'DRB4A*****'),
        ],
      ),
    );
  }
}

class TechnicalInspectionSection extends StatelessWidget {
  const TechnicalInspectionSection({super.key});

  @override
  Widget build(BuildContext context) {
    return _sectionBox(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _sectionTitle('TECHNICAL INSPECTION'),
          _inspectionGroup('Exterior Body & Paint', {
            'Front Bonnet': 'Good',
            'Front Bumper': 'Average',
            'Head Lamps': 'Good',
            'Paint Condition': 'Good',
          }),
          const SizedBox(height: 12),
          _inspectionGroup('Interior', {
            'Steering': 'Good',
            'Dashboard': 'Good',
            'Seats': 'Good',
            'AC / Heater': 'Excellent',
          }),
          const SizedBox(height: 12),
          _inspectionGroup('Engine & Mechanical', {
            'Engine Condition': 'Excellent',
            'Transmission': 'Good',
            'Chassis & Frame': 'Good',
            'Suspension & Brakes': 'Good',
          }),
        ],
      ),
    );
  }
}

class InspectionImagesSection extends StatelessWidget {
  const InspectionImagesSection({super.key});

  @override
  Widget build(BuildContext context) {
    final items = [
      'Front View',
      'Rear View',
      'Left Side',
      'Right Side',
      'Engine Bay',
      'Engine No.',
      'Odometer',
      'Chassis No.',
      'Tyre FR',
    ];

    return _sectionBox(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _sectionTitle('INSPECTION IMAGES'),
          GridView.builder(
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            itemCount: items.length,
            gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 3,
              crossAxisSpacing: 8,
              mainAxisSpacing: 8,
              childAspectRatio: 1.35,
            ),
            itemBuilder: (context, index) {
              return Stack(
                fit: StackFit.expand,
                children: [
                  Image.asset(
                    'assets/images/car_front.png',
                    fit: BoxFit.cover,
                  ),
                  Container(color: Colors.black.withOpacity(0.25)),
                  Positioned(
                    left: 6,
                    bottom: 6,
                    child: Text(
                      items[index],
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 12,
                        fontWeight: FontWeight.w900,
                      ),
                    ),
                  ),
                ],
              );
            },
          ),
        ],
      ),
    );
  }
}

class ValuationRemarksSection extends StatelessWidget {
  const ValuationRemarksSection({super.key});

  @override
  Widget build(BuildContext context) {
    return _sectionBox(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _sectionTitle('VALUATION & REMARKS'),
          Row(
            children: [
              Expanded(child: _priceBox('MARKET VALUE', 'Rs 6,80,000', 22)),
              const SizedBox(width: 10),
              Expanded(child: _priceBox('RECOMMENDED BID', 'Rs 6,80,000', 22)),
            ],
          ),
          const SizedBox(height: 14),
          const Text(
            '4W report follows the CarsRight report layout: header, summary, valuation, RC details, technical inspection, image proof and disclaimer.',
            style: TextStyle(
              color: Color(0xFF667085),
              fontSize: 14,
            ),
          ),
        ],
      ),
    );
  }
}

Widget _sectionBox({required Widget child}) {
  return Container(
    padding: const EdgeInsets.all(12),
    decoration: BoxDecoration(color: Colors.white, boxShadow: [
      BoxShadow(color: Colors.grey.withOpacity(.3), blurRadius: 10),
    ]),
    child: child,
  );
}

Widget _sectionTitle(String text) {
  return Padding(
    padding: const EdgeInsets.only(bottom: 14),
    child: Text(
      text,
      style: const TextStyle(
        color: Color(0xFF07558E),
        fontSize: 18,
        fontWeight: FontWeight.w900,
        letterSpacing: 1,
      ),
    ),
  );
}

Widget _priceBox(String label, String price, double? size) {
  return Container(
    width: double.infinity,
    padding: const EdgeInsets.all(14),
    decoration: BoxDecoration(
      color: const Color(0xFFE9FBFB),
      border: Border.all(color: const Color(0xFFB9EDF4)),
    ),
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(
            color: Color(0xFF54828E),
            fontSize: 13,
            fontWeight: FontWeight.bold,
          ),
        ),
        const SizedBox(height: 4),
        Text(
          price,
          style: TextStyle(
            color: const Color(0xFF22A7C7),
            fontSize: size,
            fontWeight: FontWeight.bold,
            letterSpacing: 1.5,
          ),
        ),
      ],
    ),
  );
}

Widget _greenTick(String text) {
  return Row(
    children: [
      const Icon(Icons.check_circle, color: Color(0xFF16A34A), size: 20),
      const SizedBox(width: 8),
      Text(
        text,
        style: const TextStyle(
          color: Color(0xFF16A34A),
          fontSize: 16,
          fontWeight: FontWeight.w900,
        ),
      ),
    ],
  );
}

Widget _twoColumn(
  String label1,
  String value1,
  String label2,
  String value2,
) {
  return Row(
    children: [
      Expanded(child: _detailCell(label1, value1)),
      Expanded(child: _detailCell(label2, value2)),
    ],
  );
}

Widget _detailCell(String label, String value) {
  return Container(
    padding: const EdgeInsets.all(10),
    decoration: BoxDecoration(
      border: Border.all(color: const Color(0xFFDDE6EE)),
    ),
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(
            color: Color(0xFF54828E),
            fontSize: 12,
            fontWeight: FontWeight.w900,
          ),
        ),
        const SizedBox(height: 5),
        Text(
          value,
          style: const TextStyle(
            color: Color(0xFF17233C),
            fontSize: 14,
            fontWeight: FontWeight.w900,
          ),
        ),
      ],
    ),
  );
}

Widget _inspectionGroup(String title, Map<String, String> rows) {
  return Container(
    padding: const EdgeInsets.all(12),
    decoration: BoxDecoration(
      color: const Color(0xFFFAFBFC),
      border: Border.all(color: const Color(0xFFDDE6EE)),
    ),
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: const TextStyle(
            color: Color(0xFF07558E),
            fontSize: 18,
            fontWeight: FontWeight.w900,
          ),
        ),
        const SizedBox(height: 10),
        ...rows.entries.map(
          (e) => Padding(
            padding: const EdgeInsets.symmetric(vertical: 7),
            child: Row(
              children: [
                Expanded(
                  child: Text(
                    e.key,
                    style: const TextStyle(
                      color: Color(0xFF17233C),
                      fontSize: 15,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
                Text(
                  e.value,
                  style: const TextStyle(
                    color: Color(0xFF07558E),
                    fontSize: 15,
                    fontWeight: FontWeight.w900,
                  ),
                ),
              ],
            ),
          ),
        ),
      ],
    ),
  );
}

class ConditionScoreInfoSection extends StatelessWidget {
  const ConditionScoreInfoSection({super.key});

  @override
  Widget build(BuildContext context) {
    return const Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Expanded(
          flex: 1,
          child: ConditionScoreCard(),
        ),
        SizedBox(width: 12),
        Expanded(
          flex: 2,
          child: ReportInfoGrid(),
        ),
      ],
    );
  }
}

class ConditionScoreCard extends StatelessWidget {
  const ConditionScoreCard({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 260,
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(color: Colors.white, boxShadow: [
        BoxShadow(color: Colors.grey.withOpacity(.3), blurRadius: 10),
      ]),
      child: Column(
        children: [
          const Spacer(),
          Stack(
            alignment: Alignment.center,
            children: [
              CircularStepProgressIndicator(
                totalSteps: 100,
                currentStep: 100,
                stepSize: 10,
                selectedColor: Colors.transparent,
                unselectedColor: Colors.transparent,
                customColor: (index) {
                  if (index < 35) {
                    return const Color(0xFF20C96B); // Green
                  } else if (index < 65) {
                    return Colors.white.withOpacity(0.15);
                  } else {
                    return const Color(0xFFE31B23); // Red
                  }
                },
              ),
              const Text(
                '64%',
                style: TextStyle(
                  color: Colors.green,
                  fontSize: 20,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
          const Text(
            'Excellent',
            style: TextStyle(
              color: Color(0xFF22C55E),
              fontSize: 16,
              fontWeight: FontWeight.w900,
            ),
          ),
          const Text(
            'Condition Score',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Color(0xFF667085),
              fontSize: 11,
              fontWeight: FontWeight.w800,
            ),
          ),
          const Spacer()
        ],
      ),
    );
  }
}

class ReportInfoGrid extends StatelessWidget {
  const ReportInfoGrid({super.key});

  @override
  Widget build(BuildContext context) {
    return _sectionBox(
      child: const Column(
        children: [
          Row(
            children: [
              Expanded(
                  child: _InfoCell(label: 'REQUESTED BY', value: 'TVS Credit')),
              Expanded(
                  child: _InfoCell(label: 'OWNER NAME', value: 'Karthik R.')),
            ],
          ),
          Row(
            children: [
              Expanded(child: _InfoCell(label: 'RC STATUS', value: 'Xerox')),
              Expanded(child: _InfoCell(label: 'HPA STATUS', value: 'Yes')),
            ],
          ),
          Row(
            children: [
              Expanded(
                  child: _InfoCell(label: 'INSURANCE', value: 'Available')),
              Expanded(
                  child: _InfoCell(
                      label: 'LENDER', value: 'TVS Credit\nServices')),
            ],
          ),
        ],
      ),
    );
  }
}

class _InfoCell extends StatelessWidget {
  final String label;
  final String value;

  const _InfoCell({
    required this.label,
    required this.value,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 78,
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
      decoration: BoxDecoration(
        border: Border.all(color: const Color(0xFFDDE6EE)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            label,
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
            style: const TextStyle(
              color: Color(0xFF54828E),
              fontSize: 12,
              fontWeight: FontWeight.w900,
            ),
          ),
          const SizedBox(height: 5),
          Text(
            value,
            maxLines: 2,
            overflow: TextOverflow.ellipsis,
            style: const TextStyle(
              color: Color(0xFF17233C),
              fontSize: 14,
              fontWeight: FontWeight.w900,
              height: 1.15,
            ),
          ),
        ],
      ),
    );
  }
}
